spring:
  profiles:
    active:
      - dog
      - EN
      - prod


guru:
  username: userYMLDefaultProfile
  password: pwYMLDefault
  jdbcurl: jdbcYMLDefault

---

spring:
  profiles: prod
guru:
  username: userProdYML
  password: pwProdYML
  jdbcurl: jdbcProdYML